import Head from "next/head";

import { useRouter } from "next/router";
import getConfig from "next/config";

import JSONTree from "react-json-tree";

import styles from "../../styles/Home.module.css";

export default function Home({ pseudoLocale }) {
  const { locales, locale, defaultLocale } = useRouter();
  const {
    publicRuntimeConfig: { sites, pseudoLocales },
  } = getConfig();

  const siteAndLocale = sites[locale] && sites[locale].locales[pseudoLocale];

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          [LOOP] <a href="https://nextjs.org">Adevinta!</a>
        </h1>
        <h1 className={styles.title}>
          {siteAndLocale
            ? siteAndLocale.title
            : `Site not found: '${locale}</strong>`}
        </h1>
        {siteAndLocale && (
          <p className={styles.description}>{siteAndLocale.description}</p>
        )}
        <div className={styles.card}>
          <h3>Props</h3>

          <p>
            locale (useRouter):{" "}
            <JSONTree data={{ locales, locale, defaultLocale }} />
          </p>
          <p>
            pseudoLocale: <JSONTree data={{ pseudoLocales, pseudoLocale }} />
          </p>
        </div>
      </main>
    </div>
  );
}

export async function getServerSideProps({
  params,
  req,
  res,
  query,
  locale,
  locales,
  defaultLocale,
}) {
  const { pseudoLocale = "es" } = params
  console.log({ params, req, res, query, locale, locales, defaultLocale });
  return {
    // redirect: {
    //   destination: `/`,
    //   permanent: false,
    // },
    props: { pseudoLocale },
  };
}

// export async function getStaticProps({
//   params: { pseudoLocale = "es" },
//   locale = "desktop",
// }) {
//   return {
//     props: {
//       pseudoLocale,
//     },
//     revalidate: 60, // Seconds. This refresh time could be longer depending on how often data changes.
//   };
// }
//
// export async function getStaticPaths({locale}) {
//   return {
//     paths: [
//       {
//         params: { pseudoLocale: "es" },
//         locale: "desktop"
//       },
//       {
//         params: { pseudoLocale: "en" },
//         locale: "desktop"
//       }
//     ],
//     fallback: true, // true -> build page if missing, false -> serve 404
//   };
// }
